### ISSUE TITLE
Not working with lasso 3.1

### ISSUE THREAD

**Issue by Eldar-X** [lasso-js/lasso-sass#7]
In lasso 3.1 i have error
```
Error: Render async fragment error (lasso-slot:head). Exception: TypeError: callback is not a function
      at Ctor.init [as doInit] (/Users/eldar-x/Projeler/NodeJs/elix-commerce/node_modules/lasso-sass/lasso-sass-plugin.j
s:40:13)
      at Ctor.init (/Users/eldar-x/Projeler/NodeJs/elix-commerce/node_modules/lasso/src/dependencies/Dependency.js:130:2
0)
      at walkDependency (/Users/eldar-x/Projeler/NodeJs/elix-commerce/node_modules/lasso/src/dependency-walker.js:66:26)
      at walkDependencies (/Users/eldar-x/Projeler/NodeJs/elix-commerce/node_modules/lasso/src/dependency-walker.js:38:1
9)
      at walkManifest (/Users/eldar-x/Projeler/NodeJs/elix-commerce/node_modules/lasso/src/dependency-walker.js:60:15)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
  Creation stack trace: Error
      at AsyncStream.beginAsync (/Users/eldar-x/Projeler/NodeJs/elix-commerce/node_modules/marko/src/runtime/html/AsyncS
tream.js:188:55)
      at render (/Users/eldar-x/Projeler/NodeJs/elix-commerce/node_modules/@lasso/marko-taglib/taglib/slot-tag.js:97:24)
      at render (/Users/eldar-x/Projeler/NodeJs/elix-commerce/node_modules/@lasso/marko-taglib/taglib/head-tag.js:16:3)
```

**Comment by austinkelleher** [comment]
@Eldar-X Thanks for the report. What version of `lasso-sass` are you using? Are you on the latest (3.0.0)?

**Comment by Eldar-X** [comment]
@austinkelleher ow i don't know how it happened but 2 days before i installed latest and it install v2 now i reinstall it and now it's v3. V3 is working thanks.
